runner_attributes:
  name: "test runner"
backend_settings:
  url: http://localhost:5000
  auth_token: <your runner token>
whisper_settings:
  hf_token: <your huggingface token>
  torch_device: cpu
  compute_type: int8
  batch_size: 4
skip_model_prefetch: true
