name: "Build & Push Docker image"
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - dev

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/Julianfp/project-w_runner
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - id: meta-dummy
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/Julianfp/project-w_runner_dummy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/julianfp/project-w_runner:buildcache
          cache-to: type=registry,ref=ghcr.io/julianfp/project-w_runner:buildcache,mode=max
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.dummy
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-dummy.outputs.tags }}
          labels: ${{ steps.meta-dummy.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/julianfp/project-w_runner_dummy:buildcache
          cache-to: type=registry,ref=ghcr.io/julianfp/project-w_runner_dummy:buildcache,mode=max
